# dependencies are handled by conda installation

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bit"
version = "1.13.6"
description = "A set of bioinformatics scripts and workflows"
readme = "README.md"
license = { text = "GPLv3" }
authors = [{ name = "Mike Lee", email = "Michael.Lee0517@gmail.com" }]
urls = { Repository = "https://github.com/AstrobioMike/bit" }
# dependencies handled by conda installation

[tool.setuptools]
packages = ["bit"]
include-package-data = true

[tool.setuptools.package-data]
bit = ["tests/data/*", "smk/*.smk", "smk/envs/*"]
